import type { Event, Participant, EventWithCount } from '@stage/shared';

export const mockEvents: EventWithCount[] = [
  {
    id: 1,
    name: 'Consid Tech Summit 2026',
    emoji: '🚀',
    slug: 'consid-tech-summit-2026',
    date: '2026-04-15',
    time: '09:00',
    end_date: '2026-04-15',
    end_time: '17:00',
    location: 'Consid Göteborg, Lilla Bommen 2',
    description: 'Årlig teknikkonferens med keynotes, workshops och networking. Tema: AI & Cloud.',
    organizer: 'Anna Lindqvist',
    organizer_email: 'anna.lindqvist@consid.se',
    status: 'upcoming',
    type: 'conference',
    max_participants: 150,
    overbooking_limit: 10,
    visibility: 'public',
    sender_mailbox: 'events@consid.se',
    gdpr_consent_text: null,
    image_url: null,
    created_by: 'anna.lindqvist@consid.se',
    created_at: '2026-02-01T10:00:00Z',
    updated_at: '2026-02-15T14:30:00Z',
    website_template: null,
    website_data: null,
    website_published: 0,
    deleted_at: null,
    participant_count: 87,
  },
  {
    id: 2,
    name: 'Workshop: React & TypeScript',
    emoji: '⚛️',
    slug: 'workshop-react-typescript',
    date: '2026-03-20',
    time: '13:00',
    end_date: '2026-03-20',
    end_time: '16:00',
    location: 'Consid Stockholm, Sveavägen 17',
    description: 'Hands-on workshop för att bygga moderna React-applikationer med TypeScript.',
    organizer: 'Erik Johansson',
    organizer_email: 'erik.johansson@consid.se',
    status: 'upcoming',
    type: 'workshop',
    max_participants: 30,
    overbooking_limit: 5,
    visibility: 'private',
    sender_mailbox: null,
    gdpr_consent_text: null,
    image_url: null,
    created_by: 'erik.johansson@consid.se',
    created_at: '2026-02-10T08:00:00Z',
    updated_at: '2026-02-10T08:00:00Z',
    website_template: null,
    website_data: null,
    website_published: 0,
    deleted_at: null,
    participant_count: 24,
  },
  {
    id: 3,
    name: 'Afterwork Q1',
    emoji: '🎉',
    slug: 'afterwork-q1',
    date: '2026-03-28',
    time: '17:00',
    end_date: null,
    end_time: null,
    location: 'Consid Malmö, Stortorget 8',
    description: 'Avslappnad afterwork för att fira Q1. Mat och dryck ingår.',
    organizer: 'Sara Berg',
    organizer_email: 'sara.berg@consid.se',
    status: 'planning',
    type: 'internal',
    max_participants: null,
    overbooking_limit: 0,
    visibility: 'private',
    sender_mailbox: null,
    gdpr_consent_text: null,
    image_url: null,
    created_by: 'sara.berg@consid.se',
    created_at: '2026-02-18T12:00:00Z',
    updated_at: '2026-02-18T12:00:00Z',
    website_template: null,
    website_data: null,
    website_published: 0,
    deleted_at: null,
    participant_count: 12,
  },
  {
    id: 4,
    name: 'Seminarium: Cloud Architecture',
    emoji: '☁️',
    slug: 'seminarium-cloud-architecture',
    date: '2026-02-10',
    time: '10:00',
    end_date: '2026-02-10',
    end_time: '12:00',
    location: 'Online (Teams)',
    description: 'Seminarium om moderna cloud-arkitekturer med fokus på kostnadsoptimering.',
    organizer: 'Lars Pettersson',
    organizer_email: 'lars.pettersson@consid.se',
    status: 'completed',
    type: 'seminar',
    max_participants: 100,
    overbooking_limit: 0,
    visibility: 'public',
    sender_mailbox: 'events@consid.se',
    gdpr_consent_text: null,
    image_url: null,
    created_by: 'lars.pettersson@consid.se',
    created_at: '2026-01-15T09:00:00Z',
    updated_at: '2026-02-10T12:30:00Z',
    website_template: null,
    website_data: null,
    website_published: 0,
    deleted_at: null,
    participant_count: 63,
  },
];

export const mockParticipants: Participant[] = [
  {
    id: 1,
    event_id: 1,
    name: 'Maria Svensson',
    email: 'maria.svensson@consid.se',
    company: 'Consid',
    category: 'internal',
    status: 'attending',
    queue_position: null,
    response_deadline: '2026-04-01',
    dietary_notes: null,
    plus_one_name: null,
    plus_one_email: null,
    cancellation_token: 'tok_abc123',
    email_status: 'delivered',
    gdpr_consent_at: '2026-02-05T10:00:00Z',
    created_at: '2026-02-05T10:00:00Z',
    updated_at: '2026-02-05T10:00:00Z',
  },
  {
    id: 2,
    event_id: 1,
    name: 'Johan Karlsson',
    email: 'johan.karlsson@example.com',
    company: 'Volvo',
    category: 'private_sector',
    status: 'attending',
    queue_position: null,
    response_deadline: '2026-04-01',
    dietary_notes: null,
    plus_one_name: null,
    plus_one_email: null,
    cancellation_token: 'tok_def456',
    email_status: 'delivered',
    gdpr_consent_at: '2026-02-06T11:00:00Z',
    created_at: '2026-02-06T11:00:00Z',
    updated_at: '2026-02-06T11:00:00Z',
  },
  {
    id: 3,
    event_id: 1,
    name: 'Karin Nilsson',
    email: 'karin.nilsson@goteborg.se',
    company: 'Göteborgs stad',
    category: 'public_sector',
    status: 'invited',
    queue_position: null,
    response_deadline: '2026-04-01',
    dietary_notes: null,
    plus_one_name: null,
    plus_one_email: null,
    cancellation_token: 'tok_ghi789',
    email_status: 'sent',
    gdpr_consent_at: null,
    created_at: '2026-02-07T09:00:00Z',
    updated_at: '2026-02-07T09:00:00Z',
  },
  {
    id: 4,
    event_id: 1,
    name: 'Anders Olsson',
    email: 'anders.olsson@consid.se',
    company: 'Consid',
    category: 'internal',
    status: 'declined',
    queue_position: null,
    response_deadline: '2026-04-01',
    dietary_notes: null,
    plus_one_name: null,
    plus_one_email: null,
    cancellation_token: 'tok_jkl012',
    email_status: 'delivered',
    gdpr_consent_at: null,
    created_at: '2026-02-08T14:00:00Z',
    updated_at: '2026-02-12T09:00:00Z',
  },
  {
    id: 5,
    event_id: 1,
    name: 'Lisa Andersson',
    email: 'lisa.andersson@consid.se',
    company: 'Consid',
    category: 'internal',
    status: 'waitlisted',
    queue_position: 1,
    response_deadline: '2026-04-01',
    dietary_notes: null,
    plus_one_name: null,
    plus_one_email: null,
    cancellation_token: 'tok_mno345',
    email_status: 'delivered',
    gdpr_consent_at: '2026-02-09T08:00:00Z',
    created_at: '2026-02-09T08:00:00Z',
    updated_at: '2026-02-09T08:00:00Z',
  },
];

export function getEventById(id: number): EventWithCount | undefined {
  return mockEvents.find((e) => e.id === id);
}

export function getParticipantsByEventId(eventId: number): Participant[] {
  return mockParticipants.filter((p) => p.event_id === eventId);
}
